python: 2.7
before_install:
    - sudo apt-get install libjpeg8-dev
install:
    - pip install -e .
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=pypy

script:
    - tox -e $TOX_ENV
