language: python
before_install:
    - sudo bash ./.setup_travis.sh
    - pip install tox cffi
env:
    - TOX_ENV=py26 JPEGLIB=jpeg8
    - TOX_ENV=py26 JPEGLIB=turbojpeg
    - TOX_ENV=py27 JPEGLIB=jpeg8
    - TOX_ENV=py27 JPEGLIB=turbojpeg
    - TOX_ENV=py33 JPEGLIB=jpeg8
    - TOX_ENV=py33 JPEGLIB=turbojpeg
    - TOX_ENV=pypy JPEGLIB=jpeg8
    - TOX_ENV=pypy JPEGLIB=turbojpeg
script:
    - tox -e $TOX_ENV
