sudo: false
language: python
addons:
    apt:
        packages:
            - libjpeg-turbo8-deva
            - libturbojpeg
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
install: pip install tox-travis
script: tox
