language: python
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install libjpeg-turbo8-dev libturbojpeg
    - pip install tox
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=pypy
script:
    - tox -e $TOX_ENV
